feature 72 integracion Backend y Frontend
JoelSoliz/hunters-food-app pull request #43
Opened 2022-11-28 04:33 UTC by Rimer-rosa

2022-11-28 04:57 UTC, JoelSoliz requested changes
Nos falta la integración de eliminar negocio de favoritos de igual modo.

2022-11-28 04:57 UTC, JoelSoliz commented on src/api/business.js
> +	const apiURL = new URL(`${HOST}/business/add_favorite/`);
El url debe ser `${HOST}/business/add_favorite?id_business=${business_id}`

2022-11-28 04:57 UTC, JoelSoliz commented on src/api/business.js
> +	apiURL.searchParams.append('id_business', business_id );
No necesario hasta la linea 59.

2022-11-28 04:57 UTC, JoelSoliz commented on src/api/business.js
> +		body: data,
No necesario porque no enviamos datos.

2022-11-28 04:57 UTC, JoelSoliz commented on src/redux/slices/business.js
> +export const addFavoriteBusiness = createAsyncThunk(
Necesitamos agregar los caso de `pending`, `fulfilled` y `failed` en los extraReducers para esta funcion.

2022-11-28 04:57 UTC, JoelSoliz commented on src/screens/businesses/Business.jsx
>  	const [isFavorite, setIsFavorite] = useState(false);
addFavorite no esta definido en el selector, revisemos bien como manejaremos el saber los negocios a los cuales le dio favorito el usuario.

2022-11-28 04:57 UTC, JoelSoliz commented on src/screens/businesses/Business.jsx
> +			dispatch(addFavoriteBusiness(value.id_business));
Esta forma va bien pero necesitamos conocer cuando lanzar la accion tomando el criterio de negocio favoroto.

2022-11-28 21:27 UTC, JoelSoliz commented on src/redux/slices/business.js
> +	async ({ business_id}) => {
En lugar de `({ business_id })` debe ser unicamente `(business_id)`

2022-11-29 01:25 UTC, JoelSoliz approved these changes

2022-11-29 01:28 UTC, mariela3810 approved these changes

2022-11-29 01:35 UTC, merged